#!/bin/bash
# ============================================================
# battery.sh — Battery status reporter for EWW.
# Reads battery information from /sys/class/power_supply.
# Returns exists:false on desktop machines so the battery
# island remains hidden without any additional configuration.
#
# Output (JSON):
#   exists  — true if a battery was found, false otherwise.
#   percent — current charge level as an integer (0-100).
#   status  — "Charging", "Discharging", "Full", or "Unknown".
#   icon    — SVG icon alias matching a file in icons/.
# ============================================================

# Search for the first available battery (BAT0 or BAT1).
BAT_PATH=""
for candidate in /sys/class/power_supply/BAT0 \
                 /sys/class/power_supply/BAT1; do
    if [ -d "$candidate" ]; then
        BAT_PATH="$candidate"
        break
    fi
done

# Return early with exists:false if no battery was found.
# This covers desktop machines and VMs without battery emulation.
if [ -z "$BAT_PATH" ]; then
    echo '{"exists":false,"percent":0,"status":"none","icon":"bat-full"}'
    exit 0
fi

PERCENT=$(cat "$BAT_PATH/capacity"   2>/dev/null || echo 0)
STATUS=$(cat  "$BAT_PATH/status"     2>/dev/null || echo "Unknown")

# Select the icon alias based on charge level and charging state.
# Icon files are generated by icon-installer.sh from material-icons SVGs.
if [ "$STATUS" = "Charging" ]; then
    ICON="bat-charging"
elif [ "$PERCENT" -le 15 ]; then
    ICON="bat-critical"
elif [ "$PERCENT" -le 30 ]; then
    ICON="bat-low"
elif [ "$PERCENT" -le 60 ]; then
    ICON="bat-mid"
elif [ "$PERCENT" -le 90 ]; then
    ICON="bat-high"
else
    ICON="bat-full"
fi

echo "{\"exists\":true,\"percent\":$PERCENT,\"status\":\"$STATUS\",\"icon\":\"$ICON\"}"
